# MM 6th Silly Sentences

name1 = input("What's your name? \n").lower().title()
name2 = input("Who is your best friend? Name..? \n").lower().title()
verb1 = input("Pick a verb ending in -ing. \n").lower()
location1 = input("Pick a location \n").lower()
adjective1 = input("Pick an adjective. \n").lower()
noun1 = input("Pick a noun. \n").lower()
verb2 = input("Pick a verb ending in -ing. \n").lower()
verb3 = input("Pick a verb in the past tense. \n").lower()
adjective2 = input("Pick an adjective. \n").lower()
verb4 = input("Pick a present tense verb. \n").lower()
adverb1 = input("Pick an adverb. \n").lower()
verb5 = input("Pick a past tense verb. \n").lower()
adjective3 = input("Pick an adjective. \n").lower()
adverb2 = input("Pick an adverb. \n").lower()
verb6 = input("Pick a past tense verb. \n").lower()
emotion1 = input("Pick a feeling, an emotion, ending in -ly. \n").lower()

print(f'{name1} and {name2} were {verb1} around in {location1} when all of the sudden a {adjective1} {noun1} came {verb2} at them. {name1} {verb3} out of the way but {name2} wasnt able to {verb4} the {adjective1} {noun1} so {name2} {adverb1} {verb5}. {name1} was very {adjective3} about this and {adverb2} {verb6} away very {emotion1}. ')